export const inventarioInicial = [
  {
    id: 1,
    nombre: "Teclado Mecánico RGB",
    precio: 85000,
    stock: 15,
    descripcion: "Teclado con switches rojos, retroiluminación RGB personalizable.",
    categoria: "perifericos",
  },
  {
    id: 2,
    nombre: "Mouse Inalámbrico Gaming",
    precio: 45000,
    stock: 5,
    descripcion: "Mouse ergonómico con sensor óptico de alta precisión y 7 botones programables.",
    categoria: "perifericos",
  },
  {
    id: 3,
    nombre: "SSD 1TB NVMe",
    precio: 250000,
    stock: 10,
    descripcion: "Unidad de estado sólido NVMe de alta velocidad para cargas rápidas.",
    categoria: "almacenamiento",
  },
  {
    id: 4,
    nombre: "Audífonos Bluetooth Noise Cancelling",
    precio: 120000,
    stock: 0,
    descripcion: "Audífonos con cancelación de ruido activa y batería de larga duración.",
    categoria: "audio",
  },
  {
    id: 5,
    nombre: 'Monitor Curvo 27"',
    precio: 750000,
    stock: 25,
    descripcion: "Monitor gaming curvo con resolución Full HD y 144Hz de refresco.",
    categoria: "monitores",
  },
  {
    id: 6,
    nombre: "Webcam Full HD",
    precio: 35000,
    stock: 8,
    descripcion: "Cámara web con resolución 1080p y micrófono integrado.",
    categoria: "perifericos",
  },
  {
    id: 7,
    nombre: "Memoria RAM 16GB DDR4",
    precio: 180000,
    stock: 7,
    descripcion: "Módulo de memoria RAM de alto rendimiento para gaming y multitarea.",
    categoria: "componentes",
  },
  {
    id: 8,
    nombre: "Router Wi-Fi 6",
    precio: 90000,
    stock: 18,
    descripcion: "Router de última generación con tecnología Wi-Fi 6 para conexiones rápidas.",
    categoria: "redes",
  },
  {
    id: 9,
    nombre: "Disco Duro Externo 4TB",
    precio: 150000,
    stock: 12,
    descripcion: "Almacenamiento portátil de gran capacidad con conexión USB 3.0.",
    categoria: "almacenamiento",
  },
  {
    id: 10,
    nombre: "Computadora de Escritorio Gamer",
    precio: 3500000,
    stock: 2,
    descripcion: "Potente PC gamer con procesador de última generación y tarjeta gráfica RTX.",
    categoria: "computadoras",
  },
  {
    id: 11,
    nombre: "Silla Gamer Ergonómica",
    precio: 300000,
    stock: 5,
    descripcion: "Silla ergonómica diseñada para largas sesiones de juego o trabajo.",
    categoria: "muebles",
  },
  {
    id: 12,
    nombre: "Smartwatch Deportivo",
    precio: 200000,
    stock: 1,
    descripcion: "Reloj inteligente con funciones de monitoreo de actividad y ritmo cardíaco.",
    categoria: "relojes",
  },
];
